@echo off
REM Configuration script - Run this after getting your tunnel URLs
REM Usage: configure-app.bat FRONTEND_URL BACKEND_URL

setlocal enabledelayedexpansion

if "%~1"=="" (
    echo Error: Missing FRONTEND_URL
    echo.
    echo Usage: configure-app.bat FRONTEND_URL BACKEND_URL
    echo.
    echo Example:
    echo configure-app.bat https://abc.trycloudflare.com https://xyz.trycloudflare.com
    echo.
    pause
    exit /b 1
)

if "%~2"=="" (
    echo Error: Missing BACKEND_URL
    echo.
    echo Usage: configure-app.bat FRONTEND_URL BACKEND_URL
    echo.
    echo Example:
    echo configure-app.bat https://abc.trycloudflare.com https://xyz.trycloudflare.com
    echo.
    pause
    exit /b 1
)

set FRONTEND_URL=%~1
set BACKEND_URL=%~2

echo ============================================
echo Configuring Your Telegram Mini App
echo ============================================
echo.
echo Frontend URL: %FRONTEND_URL%
echo Backend URL:  %BACKEND_URL%
echo.

REM Create .env.local for frontend
echo Creating frontend\.env.local...
(
echo # Telegram Mini App - Local Development
echo # Auto-generated by configure-app.bat
echo.
echo NEXT_PUBLIC_API_URL=%BACKEND_URL%/api
) > frontend\.env.local

if exist "frontend\.env.local" (
    echo [OK] Created frontend\.env.local
) else (
    echo [ERROR] Failed to create frontend\.env.local
    pause
    exit /b 1
)

echo.
echo ============================================
echo Configuration Summary
echo ============================================
echo.
echo [OK] Frontend environment configured
echo     File: frontend\.env.local
echo     API URL: %BACKEND_URL%/api
echo.
echo.
echo ============================================
echo IMPORTANT: Update Backend CORS
echo ============================================
echo.
echo You need to add these URLs to backend\main.py:
echo.
echo     "%FRONTEND_URL%",
echo     "%BACKEND_URL%",
echo.
echo Add them to BOTH allow_origins lists (lines ~98 and ~134)
echo.
echo After updating, restart your backend server:
echo     cd backend
echo     uvicorn main:app --reload --port 8080
echo.
echo.
echo ============================================
echo Configure Telegram Bot
echo ============================================
echo.
echo 1. Open Telegram and search for: @BotFather
echo 2. Send: /mybots
echo 3. Select: Bahamm_bot
echo 4. Choose: Bot Settings ^> Menu Button
echo 5. Enter this URL:
echo.
echo     %FRONTEND_URL%
echo.
echo.
echo Configuration complete!
echo.
pause



